import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        secondary: "#00696f",
        "outline-variant": "#c1c6d7",
        "surface-bright": "#f9f9f9",
        "on-primary-container": "#fefcff",
        "on-secondary-fixed-variant": "#004f54",
        outline: "#717786",
        "on-secondary-fixed": "#002022",
        "on-primary-fixed-variant": "#004493",
        "surface-container-high": "#e8e8e8",
        "inverse-on-surface": "#f0f1f1",
        tertiary: "#9e3d00",
        primary: "#0058bc",
        "tertiary-fixed-dim": "#ffb595",
        "primary-container": "#0070eb",
        "on-surface-variant": "#414755",
        "on-error": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        "inverse-primary": "#adc6ff",
        "surface-dim": "#dadada",
        "surface-container": "#eeeeee",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#351000",
        "inverse-surface": "#2f3131",
        surface: "#f9f9f9",
        "surface-tint": "#005bc1",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-container": "#c64f00",
        "on-error-container": "#93000a",
        "secondary-fixed": "#74f5ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed": "#001a41",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "secondary-container": "#00f1fe",
        "surface-container-low": "#f3f3f3",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "on-secondary-container": "#006a70",
        "secondary-fixed-dim": "#00dbe7",
        "on-tertiary-fixed-variant": "#7c2e00",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        serif: ["var(--font-noto-serif)"],
        sans: ["var(--font-inter)"],
        mono: ["var(--font-space-grotesk)"],
      },
    },
  },
  plugins: [],
};
export default config;
